### ISSUE TITLE
Non-reproducable OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by koreyou** [koreyou/chainerboard#5]
chainerboard sometimes give out following error.

```
INFO:werkzeug:127.0.0.1 - - [15/Aug/2017 14:14:09] "POST /events/updates HTTP/1.1" 200 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/koreyou/.pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/chainerboard/lib/python2.7/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/chainerboard/lib/python2.7/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/chainerboard/lib/python2.7/site-packages/watchdog/events.py", line 330, in dispatch
    _method_map[event_type](event)
  File "/home/koreyou/work/chainerboard/chainerboard/watcher.py", line 24, in on_modified
    if os.path.samefile(event.src_path, self._watch_path):
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/chainerboard/lib/python2.7/posixpath.py", line 155, in samefile
    s1 = os.stat(f1)
OSError: [Errno 2] No such file or directory: '/home/koreyou/work/abae-chainer/result/logK5E4nK'
```

This happened when I am trying to monitor "/home/koreyou/work/abae-chainer/result/log" .

Running the same command sometimes give out the same error but other times not.

**Comment by koreyou** [comment]
This is because chainer's ``LogReport`` uses safe copy mechanism to write the final log:

```
            # write to the log file
            if self._log_name is not None:
                log_name = self._log_name.format(**stats_cpu)
                fd, path = tempfile.mkstemp(prefix=log_name, dir=trainer.out)
                with os.fdopen(fd, 'w') as f:
                    json.dump(self._log, f, indent=4)

                new_path = os.path.join(trainer.out, log_name)
                shutil.move(path, new_path)
```
