### ISSUE TITLE
KeyError in get_events_updates when log was altered

### ISSUE THREAD

**Issue by koreyou** [koreyou/chainerboard#6]
I made a program with custom evaluator which reports  metrics at `validation_1/topic_match/*` (e.g. `validation_1/topic_match/f1_9`). Loading this log data results in KeyError

```python
INFO:werkzeug:127.0.0.1 - - [02/Sep/2017 11:32:53] "POST /events/updates HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/abae-chainer/lib/python2.7/site-packages/chainerboard/app/events.py", line 143, in get_events_updates
    if timeline_handler.events[g].state_hash != states.get(g, ''):
KeyError: u'f1_9'
```

**Comment by koreyou** [comment]
this is reproducible with the attached log file

[log.txt](https://github.com/koreyou/chainerboard/files/1271851/log.txt)

**Comment by koreyou** [comment]
This is NOT actually reproducible provided log file.
This was actually caused by old session on browser; Old session was querying for events that does not exist.

You can reproduce the problem by altering the existing file.

```
for i in {0..100}; do sed -i "s/f1_108/f1_18/g" ~/Desktop/log; sleep 0.5s;sed -i "s/f1_18/f1_108/g" ~/Desktop/log ; done
```
